import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/top-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>CrimesonHouse</title>
        <link rel="icon" href="/image/LOGO-t-01.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} hidden lg:block`}
      >
        <TopBar />
        {children}
      </body>
    </html>
  );
}
